### Make HTTP request and write the CSV file
POST http://localhost:8080/api/astronauts

### Storage the information and get the info as JSON
GET http://localhost:8080/api/astronauts

### Brings an ordered asc list of astronauts
GET http://localhost:8080/api/astronauts/asc

### Brings an ordered desc list of astronauts
GET http://localhost:8080/api/astronauts/desc
