// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/josedejesusAmaya/golang-bootcamp-2020/mocks/service (interfaces: AstronautService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/josedejesusAmaya/golang-bootcamp-2020/domain"
	errs "github.com/josedejesusAmaya/golang-bootcamp-2020/errs"
)

// MockAstronautService is a mock of AstronautService interface
type MockAstronautService struct {
	ctrl     *gomock.Controller
	recorder *MockAstronautServiceMockRecorder
}

// MockAstronautServiceMockRecorder is the mock recorder for MockAstronautService
type MockAstronautServiceMockRecorder struct {
	mock *MockAstronautService
}

// NewMockAstronautService creates a new mock instance
func NewMockAstronautService(ctrl *gomock.Controller) *MockAstronautService {
	mock := &MockAstronautService{ctrl: ctrl}
	mock.recorder = &MockAstronautServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAstronautService) EXPECT() *MockAstronautServiceMockRecorder {
	return m.recorder
}

// GetAllAstronauts mocks base method
func (m *MockAstronautService) GetAllAstronauts() ([]domain.Astronaut, *errs.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAstronauts")
	ret0, _ := ret[0].([]domain.Astronaut)
	ret1, _ := ret[1].(*errs.Error)
	return ret0, ret1
}

// GetAllAstronauts indicates an expected call of GetAllAstronauts
func (mr *MockAstronautServiceMockRecorder) GetAllAstronauts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAstronauts", reflect.TypeOf((*MockAstronautService)(nil).GetAllAstronauts))
}

// GetAscAstronauts mocks base method
func (m *MockAstronautService) GetAscAstronauts() ([]domain.Astronaut, *errs.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAscAstronauts")
	ret0, _ := ret[0].([]domain.Astronaut)
	ret1, _ := ret[1].(*errs.Error)
	return ret0, ret1
}

// GetAscAstronauts indicates an expected call of GetAscAstronauts
func (mr *MockAstronautServiceMockRecorder) GetAscAstronauts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAscAstronauts", reflect.TypeOf((*MockAstronautService)(nil).GetAscAstronauts))
}

// GetDescAstronauts mocks base method
func (m *MockAstronautService) GetDescAstronauts() ([]domain.Astronaut, *errs.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescAstronauts")
	ret0, _ := ret[0].([]domain.Astronaut)
	ret1, _ := ret[1].(*errs.Error)
	return ret0, ret1
}

// GetDescAstronauts indicates an expected call of GetDescAstronauts
func (mr *MockAstronautServiceMockRecorder) GetDescAstronauts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescAstronauts", reflect.TypeOf((*MockAstronautService)(nil).GetDescAstronauts))
}
